# TODO: Update Name
name: project_base
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # I18N Dependencies
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1

  animations: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.4
  import_sorter: ^4.4.1

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  ios: true
  image_path_ios: "assets/icon/ios_icon.png"
  android: true
  image_path_android: "assets/icon/android_icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/lang/